name: "Flatpak Manager"
description: "Deploy your Flatpak application to a repository"
author: "Bilal Elmoussaoui"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  repository:
    description: >
      The Flatpak repository to push the build into.
    required: true
  flat-manager-url:
    description: >
      The flat-manager repository URL.
    required: true
  token:
    description: >
      A flat-manager token to publish into the repository.
    required: true
  end-of-life:
    description: >
      Mark build as end-of-life.
    required: false
  end-of-life-rebase:
    description: >
      "Mark new refs as end-of-life. This one takes an ID that supersedes the current one. By the user's request, the application data may be preserved for the new application. Note, this is actually a prefix match, so if you say org.the.app=org.new.app, then something like org.the.app.Locale will be rebased to org.new.app.Locale."
    required: false
  verbose:
    description: >
      "Enable verbosity"
    required: false
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
