#!/usr/bin/env python3

# The latest version of this script can be found at
# https://gitlab.gnome.org/GNOME/gnome-runtime-images

import json
from ruamel import yaml
import os, sys

from contextlib import contextmanager


@contextmanager
def rewrite_manifest(filename):
    with open(filename) as f:
        if filename.endswith(".json"):
            data = json.load(f)
        else:
            data = yaml.round_trip_load(f, preserve_quotes=True)

    yield data

    with open(filename, "w") as f:
        if filename.endswith(".json"):
            json.dump(data, f, indent=4, separators=(",", " : "))
        else:
            yaml.round_trip_dump(data, f)


if __name__ == "__main__":
    try:
        manifestfile, modulename, run_tests = sys.argv[1:]
    except ValueError:
        print("usage: {} flatpak_manifest module_name".format(sys.argv[0]))
        sys.exit(1)
    run_tests = run_tests == "true"
    with rewrite_manifest(manifestfile) as data:

        if run_tests:
            build_options = data.get("build-options", {})
            build_options["env"] = data.get("env", {})
            build_options["env"]["DISPLAY"] = "0:0"
            build_options["test-args"] = [
                "--share=network",
                "--socket=x11",
            ]
            data["build-options"] = build_options

        for mod in data["modules"]:
            if not isinstance(mod, dict):
                continue

            if mod["name"] == modulename:
                mod["run-tests"] = run_tests
                for i in range(0, len(mod["sources"])):
                    if not mod["sources"][i]["type"] == "git":
                        continue
                    path = os.path.relpath(".", os.path.dirname(manifestfile))
                    mod["sources"][i] = {"type": "dir", "path": path}
