on:
  push:
    branches: [master]
  pull_request:

name: Codespell

jobs:
  codespell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: "./.git/**,./flat-manager/dist/index.js,./flatpak-builder/dist/index.js,**/yarn.lock"
          builtin: "clear,rare,informal,usage,code"
          ignore_words_list: "master" # can't do much about it, flatpak uses it by default
